"""Create testcases table

Revision ID: 47f07a57075b
Revises: 52547cda9fd4
Create Date: 2025-09-25 15:38:03.351173

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47f07a57075b'
down_revision = '52547cda9fd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_user_badge', table_name='user_badges')
    op.drop_table('user_badges')
    op.drop_index('idx_problems_stars', table_name='problems')
    op.drop_index('idx_problems_tags', table_name='problems')
    op.drop_column('problems', 'examples')
    op.drop_column('testcases', 'time_complexity')
    op.drop_column('testcases', 'space_complexity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testcases', sa.Column('space_complexity', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True))
    op.add_column('testcases', sa.Column('time_complexity', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True))
    op.add_column('problems', sa.Column('examples', mysql.JSON(), nullable=True))
    op.create_index('idx_problems_tags', 'problems', [], unique=False)
    op.create_index('idx_problems_stars', 'problems', ['stars'], unique=False)
    op.create_table('user_badges',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('badge_key', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('assigned_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('unique_user_badge', 'user_badges', ['user_id', 'badge_key'], unique=False)
    # ### end Alembic commands ###
