"""Initial clean migration

Revision ID: 52547cda9fd4
Revises: 27dccd5291b7
Create Date: 2025-09-18 13:07:15.119893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52547cda9fd4'
down_revision = '27dccd5291b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
